### ISSUE TITLE
PennyLane PyQVM support requires Quilc running with pyQuil>=2.8

### ISSUE THREAD

**Issue by josh146** [rigetti/pennylane-forest#15]
For now, to use PennyLane-Forest with the PyQVM, you will need to have the Quilc servers running. See https://github.com/rigetti/pyquil/issues/924 for more details.

**Comment by karalekas** [comment]
@josh146 The pyQVM doesn't require the QVM to be running, just quilc (for now).

**Comment by josh146** [comment]
Thanks! have updated the title

**Comment by karalekas** [comment]
This should be fixed in v2.9.1! :)

**Comment by josh146** [comment]
Closing due to fix implemented in https://github.com/rigetti/pyquil/pull/934
