### ISSUE TITLE
QVMError involving Pragma INITIAL_REWIRING

### ISSUE THREAD

**Issue by msohaibalam** [rigetti/pennylane-forest#2]
If I run
```
import pennylane as qml
from pennylane import numpy as np


dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circuit(var):
    qml.RX(var[0], wires=0)
    qml.RZ(var[1], wires=1)
    return qml.expval.PauliZ(0)


var0 = [np.pi/2, 0]
z = circuit(var0)
print (z)
```
I get the expected output `4.440892098500626e-16` (a number close to `0`).

However, if I run
```
import pennylane as qml
from pennylane import numpy as np


qvm = qml.device('forest.qvm', 
                 device='9q-qvm',
                 shots=100,
                 active_reset=True)

@qml.qnode(qvm)
def circuit(var):
    qml.RX(var[0], wires=0)
    qml.RZ(var[1], wires=1)
    return qml.expval.PauliZ(0)


var0 = [np.pi/2, 0]
z = circuit(var0)
print (z)
```
I get the error message:
```
QVMError: Malformed pragma INITIAL_REWIRING -- argument count mismatch

The QVM returned the above error. This could be due to a bug in the server or a
bug in your code. If you suspect this to be a bug in pyQuil or Rigetti Forest,
then please describe the problem in a GitHub issue at:
    https://github.com/rigetti/pyquil/issues
```

It's unclear if this is a bug, or because my QVM/Quilc is outdated.

**Comment by josh146** [comment]
Hi @msohaibalam, it works fine for me, using my locally installed version of qvm and quilc. Versions I'm using are:

* pyQuil version 2.3,
* QuilC version `1.1.0 (library: 1.1.0) [e1f1533]`,
* QVM version `1.1.0 (library: 1.1.0) [a8e5ee8]`).

Running your second example gives the following result for `z`:
```python
-0.04
```

What version of the Forest SDK/QuilC/QVM are you using? @kmckiern, do you have any insights I might be missing?

**Comment by kmckiern** [comment]
I'm not able to reproduce this error. I ran the same code both locally, and on my QMI, both times a reasonable result was returned (around 0.04).

Local configuration:
- pyquil 2.3.0
- qvm `1.0.1 (library: 1.0.1) [2202582]`
- quilc `1.0.2 (library: 1.0.2) [4037649]`

**Comment by msohaibalam** [comment]
That's odd. I have:

- pyQuil version 2.4.0.dev0
- qvm `1.0.1 (library: 1.0.1) [2202582]`
- quilc `1.2.0 (library: 1.2.0) [47523da]`

so it doesn't seem like updating any of the above would help (I could still try though). Perhaps it's the opposite problem, i.e. a later version of either pyQuil or quilc causes this (?)

**Comment by josh146** [comment]
Could it be an API change going from pyquil 2.3.0->2.4.0.dev0? An easy check would be to do a quick pip downgrade, and see if that resolves the issue

**Comment by msohaibalam** [comment]
Downgrading to pyQuil 2.3.0 did not fix my problem. However, upgrading both my qvm and quilc versions to `1.3.2` fixed it.

**Comment by josh146** [comment]
strange :thinking:

**Comment by kmckiern** [comment]
I suppose the take away is to not let the qvm and quilc versions diverge too much.

**Comment by msohaibalam** [comment]
^ I'd add pyQuil to that too. The latest quilc wants you to use it in the `-R` (RPCQ) server mode instead of the `-S` (HTTP) server mode. However, I run into problems with even simple pyQuil programs if I try to use `quilc -R` with pyQuil 2.3.0 which go away if I either (a) use `quilc -S`, or (b) use pyquil 2.4.0.dev0 instead.

But I agree, this is indeed strange. In case someone else does run into this issue though, updating everything to latest versions does seem to work.
