### ISSUE TITLE
Illegal qubits when using QPU

### ISSUE THREAD

**Issue by josh146** [rigetti/pennylane-forest#20]
When using the QVM to simulate hardware devices such as Aspen-4-9Q-A, i.e.,

```python
qml.device("forest.qvm", device="Aspen-4-9Q-A")
```

PennyLane-Forest works as expected. From the main interface, PL wires (labeled 0-8) are converted to match the topology of the QPU (labelled 0,1,2,7,10,11,15,16,17).

However, when attempting to run the exact same program on the QPU,

```python
qml.device("forest.qpu", device="Aspen-4-9Q-A")
```

it produces the error
```python
Error: "Program instruction RX(pi/4) attempts to use illegal qubits: 3. Illegal qubits on this QPU: 3, 4, 5, 6, 8, 9, 12, 13"
```

Is there an error in how PennyLane-Forest perform the 'rewiring' of qubits for the QPU? Ideally, a computation with qubits labelled 0-8 should run seamlessly and be rewired behind the scenes for the user.

EDIT/UPDATE: There are two related issues here: (i) the one outlined above, and (ii) the in-ability to run programs on legal qubits on the lattice. Issue (i) can be illustrated by the following code snippet
```
import pennylane as qml
from pennylane import numpy as np

qpu = qml.device("forest.qpu", device="Aspen-4-4Q-E")
print(qpu.qc.qubits())  # [10, 11, 12, 17]

@qml.qnode(qpu)
def circuit(angle):
    qml.RY(angle, wires=0)
    return qml.expval(qml.PauliZ(0))

circuit(np.pi/2)   # raises `RPCError: Program instruction 'RY(pi/2) 0' attempts to use illegal qubits: 0. Illegal qubits on this QPU: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 14, 15, 16.`
```

while issue (ii) can be illustrated by the following code snippet
```
import pennylane as qml
from pennylane import numpy as np

qpu = qml.device("forest.qpu", device="Aspen-4-4Q-E")
print(qpu.qc.qubits())  # [10, 11, 12, 17]

@qml.qnode(qpu)
def circuit(angle):
    qml.RY(angle, wires=10)
    return qml.expval(qml.PauliZ(10))

circuit(np.pi/2)    # raises `QuantumFunctionError: Operation RY applied to invalid wire 10 on device with 4 wires.`
```

**Comment by msohaibalam** [comment]
Hi @josh146 , good to play around with pennylane-forest code after my break!
Question: is this still an issue? Using the latest versions on master (for both pennylane and pennylane-forest, not yet having merged the operator_estimation PR), I see that the following code runs without problem. Note that this happens despite qubit 0 being an illegal qubit on the lattice (I had to use a different example from yours, since `Aspen-4-9Q-A` has since been retired).

```
import pennylane as qml
from pennylane import numpy as np

qpu = qml.device("forest.qpu", device="Aspen-4-4Q-E")
print(qpu.qc.qubits())  # [10, 11, 12, 17]

@qml.qnode(qpu)
def circuit(angle):
    qml.RY(angle, wires=0)
    return qml.expval(qml.PauliZ(0))

circuit(np.pi/2)   # runs fine
```

**Comment by msohaibalam** [comment]
However, note that the somewhat related problem of actually trying to specify a qubit that one would like to run a circuit on, and which is a legal qubit on the lattice. For example,
```
import pennylane as qml
from pennylane import numpy as np

qpu = qml.device("forest.qpu", device="Aspen-4-4Q-E")
print(qpu.qc.qubits())  # [10, 11, 12, 17]

@qml.qnode(qpu)
def circuit(angle):
    qml.RY(angle, wires=10)
    return qml.expval(qml.PauliZ(10))

circuit(np.pi/2)    # raises `QuantumFunctionError: Operation RY applied to invalid wire 10 on device with 4 wires.`
```
I think this latter problem should be easy enough to fix.

**Comment by msohaibalam** [comment]
Ok nevermind, I was able to recover the original error msg after merging in the operator_estimation PR. I'm going to try to knock out both these issues at the same time.

**Comment by josh146** [comment]
I believe this is now solved, so closing this issue :)
