### ISSUE TITLE
How come you don't use memory_map dict as qc.run() argument?

### ISSUE THREAD

**Issue by rrtucci** [rigetti/pennylane-forest#7]
According to the Forest docs, the "new way" of minimizing an anzatz does the following:
1. declares parameters in the program, and
2. uses the memory_map dict as an argument to qc.run(). 

But your classes
 device, ForestDevice, qvm, qpu
none of them does this. Is this then the "old way" of minimizing the anzatz? If so, why are you using the old way?

**Comment by josh146** [comment]
Hi @rrtucci, you raise a good point. PennyLane and the Forest plugin were developed right before parametric compilation was supported in pyQuil (using pyQuil v1.9), so at the time, the plugin was designed around the 'old' way.

It would be great to also support pyQuil v2 style parametric programs.

One complication is that PennyLane takes care of the symbolic variables automatically, and passes the resulting numeric values to the plugin device when an evaluation is needed. This just means that the core PennyLane library will also need a pull request to have the core library pass which parameters are symbolic to the plugin.

**Comment by josh146** [comment]
@msohaibalam, any thoughts?

**Comment by rrtucci** [comment]
Thanks, Josh. I am learning a tremendous amount from PennyLane. You are a great programmer

**Comment by msohaibalam** [comment]
Thanks for bringing attention to this! The important point is that your parametric program gets compiled once in order to avoid compilation overheads, so that you can scan over several parameters without re-compiling.

@josh146 Correct me if I'm wrong, but in the current set-up, we're limited to doing operations like the following:

```
import pennylane as qml
from pennylane import numpy as np


qvm = qml.device('forest.qvm', device='2q-qvm', wires=2, shots=1000)

@qml.qnode(qvm)
def circuit(theta):
    qml.RX(theta, wires=0)
    return qml.expval.PauliZ(0)

print(circuit(np.pi/2))
```

And if we do something like 
```
import pennylane as qml
from pennylane import numpy as np


qvm = qml.device('forest.qvm', device='2q-qvm', wires=2, shots=1000)

@qml.qnode(qvm)
def circuit():
    for theta in np.linspace(0.0, np.pi, 100):
        qml.RX(theta, wires=0)
        yield qml.expval.PauliZ(0)

print(list(circuit()))
```
we'll get the error msg: `QuantumFunctionError: A quantum function must return either a single expectation value or a nonempty sequence of expectation values.`

It would make more sense to use and support memory_map in qc.run() for something like the latter example.

**Comment by josh146** [comment]
Yes, that sums it up well. I'll have a think about it, and see if this is something that we can easily support in PennyLane.

**Comment by rrtucci** [comment]
I've done a very primitive, naive implementation with my software Qubiter. It does the minimization with scipy so it is still very far from the level of sophistication of PennyLane. But it does establish the feedback loop between my machine and rigetti's, and does the minimization in my machine, just like Pennylane does. The BIG part missing compared to Pennylane is that in my machine I do scipy minimization instead of backpropagation. That is a future plan. I haven't tested it because I don't have a Rigetti account, despite requesting one. Anyway here it is. Stil very early and buggy
https://github.com/artiste-qb-net/qubiter/blob/master/adv_applications/MeanHamilMinimizer_rigetti.py

**Comment by rrtucci** [comment]
One subtlety: the parametric stuff of Rigetti seems to provide an advantage only if the program is fixed while the parameter theta varies. If one is minimizing a general hamiltonian, that will never be the case unless the hamiltonian being minimized is expressible as a single Term= a tensor product of pauli matrices. If it is expressible as a sum of a Terms, as the most general Hermitian matrices are, then you have to vary the program for each Term, and at fixed theta.

**Comment by rrtucci** [comment]
I think the solution to this conundrum is to store a dictionary that maps each pauli Term with its executable

**Comment by msohaibalam** [comment]
> One subtlety: the parametric stuff of Rigetti seems to provide an advantage only if the program is fixed while the parameter theta varies.

@rrtucci Yes, that's correct. In typical variational hybrid classical/quantum algorithms, such as [QAOA](https://arxiv.org/abs/1411.4028) or [VQE](https://arxiv.org/abs/1509.04279), one prepares trial states as a function of some continuous parameters, and then tries to minimize the expectation value of some fixed Hamiltonian in such trial states. Parametric compilation makes this process faster on the QPU.

As far as being able to minimize several terms in a Hamiltonian together, this can in principle be done for terms that are diagonal in the same "tensor product basis" (in the sense of [https://arxiv.org/pdf/1704.05018v2.pdf Section V. A](https://arxiv.org/pdf/1704.05018v2.pdf); note that this is a stronger condition than commutation). We're working on making this easier to do with pyquil. An effort in this direction is the currently WIP PR, for example: https://github.com/rigetti/pyquil/pull/829

**Comment by rrtucci** [comment]
No need to restrict the hamiltonian in anyway. I suggest you use the Pyquil classes PauliTerm and PauliSum 
https://github.com/rigetti/pyquil/blob/master/pyquil/paulis.py
I have already implemented all this in Qubiter using the class QubitOperator from OpenFermion, which is equivalent to your classes PauliTerm and PauliSum. Like I said last night, what I do is store the executable for each Pauli Term and keep reusing them
https://github.com/artiste-qb-net/qubiter/blob/master/adv_applications/MeanHamilMinimizer_rigetti.py

**Comment by rrtucci** [comment]
You may have to express your Hamiltonian as a sum of Pauli Terms if it us nit given that way a priori, for i stance, if it is given as a numoy array. But I think that is not too hard. I haven't checked, but OpenFermion probably has a function that translates numpy arrays to Pauli sums and back

**Comment by msohaibalam** [comment]
Sorry, I should've clarified: what I meant to say is even if you have a sum of several PauliTerms (and so, a PauliSum, to use pyQuil lingo), you could in principle just apply the same program to a group of PauliTerms that are diagonal in the same "tensor product basis". Perhaps this could produce a smaller dictionary (to use your strategy) compared to if you choose to identify each dict key as a separate PauliTerm.

**Comment by rrtucci** [comment]
Yes. Thanks

**Comment by tmittal947** [comment]
Hi @rrtucci, We appreciate your feedback and are happy to set you up with beta access to QCS. You should receive an email in a few minutes with the subject "You're invited to join Rigetti QCS."

**Comment by rrtucci** [comment]
Thanks for the Rigetti cloud account. Much appreciated @tmittal947 
@msohaibalam
 I was thinking that storing the executable for each pauli term is indeed hiddeously wasteful because aany two of those executables only differ in their last few commands that pertain to their Pauli Term. It should be possible to store the common part of the executable, and then a dictionary mapping each pauli term to the Pauli dependent ending of the executable. This would entail defining __add__ for executables. Then in the run function, one passes

 pauli_term_indep_beginning_of executable + 
pauli_term_to_pauli_term_dependent_executable[pauli_term]
